export const AUTH_SUCCESS = 'AUTH_LOGIN'
export const AUTH_ERROR = 'AUTH_ERROR'
export const API_START = 'API_START'
export const API_END = 'API_END'
export const UPDATE_USER_SESSION = 'UPDATE_USER_SESSION'
export const ACTIVE_SIDEBAR = 'ACTIVE_SIDEBAR'
export const GET_EVENT = 'GET_EVENT'
export const EVENT_ERROR = 'EVENT_ERROR'
