export const AUTH_SUCCESS = 'AUTH_LOGIN'
export const AUTH_ERROR = 'AUTH_ERROR'
export const AUTH_START = 'AUTH_START'
export const AUTH_END = 'AUTH_END'
export const UPDATE_USER_SESSION = 'UPDATE_USER_SESSION'
